"use client";
import { ChakraProvider } from "@chakra-ui/react";
import { Box } from "@chakra-ui/react";
import Navbar from "./components/NavBar";
import { theme } from "./chakra/theme";

//export const metadata = {
//	title: "Create Next App",
//	description: "Generated by create next app",
//};

//

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>
          <Navbar />
          <Box>{children}</Box>
        </ChakraProvider>
      </body>
    </html>
  );
}

//Page Specific Styling

export default RootLayout;
