"use client";
import { ChakraProvider } from "@chakra-ui/react";
import { Box } from "@chakra-ui/react";
import Navbar from "./components/NavBar";
import { theme } from "./chakra/theme";
import { AuthProvider } from "./firebase/AuthProvider";
import { UserCredential } from "firebase/auth";

//export const metadata = {
//	title: "Create Next App",
//	description: "Generated by create next app",
//};

//

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>
          <AuthProvider>
            <>
              <Navbar />
              <Box>{children}</Box>
            </>
          </AuthProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}

//Page Specific Styling

export default RootLayout;
